export const ActionTypes = {
	USER: {
		SET_LOGIN: "SET_LOGIN",
		UPDATE_USER: "UPDATE_USER",
		LOGOUT: "LOGOUT",
	},
	EVENT: {
		CREATE_EVENT: "CREATE_EVENT",
		ALL_EVENTS: "ALL_EVENTS",
		SELECTED_EVENT: "SELECTED_EVENT",
		REMOVE_EVENT: "REMOVE_EVENT",
		UPDATE_EVENT: "UPDATE_EVENT",
	},
};
